lib/spatracker_web/router.ex
defmodule SpatrackerWeb.Router do
  use SpatrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpatrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpatrackerWeb do
  #   pipe_through :api
  # end

  scope "/api/v1", SpatrackerWeb do
    pipe_through :api

    resources "/users", UserController, except: [:new, :edit]
    resources "/tasks", TaskController, except: [:new, :edit]
    post "/auth", AuthController, :authenticate
  end
end

lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TasktrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, [":json"]
    plug :fetch_session
    plug :fetch_flash
    plug TasktrackerWeb.Plugs.FetchSession #FIXME "FetchUser"
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TasktrackerWeb do
    pipe_through :ajax
    resources "/timeblocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/spatracker/tasks.ex
defmodule Spatracker.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias Spatracker.Repo

  alias Spatracker.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id), do: Repo.get!(Task, id)

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
end

lib/spatracker/tasks/task.ex
defmodule Spatracker.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tasks" do
    field :name, :string
    field :complete, :boolean, default: false
    field :desc, :string
    field :time, :integer
    belongs_to :user, Spatracker.Users.User

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    attrs = if attrs != nil && Map.has_key?(attrs, "assignee") &&
               Spatracker.Users.get_user_by_name(attrs["assignee"]) do
      user = Spatracker.Users.get_user_by_name(attrs["assignee"])
      Map.put(attrs, "user_id", user.id)
      |> Map.delete("assignee")
    else
    attrs
  end
  task
    |> cast(attrs, [:complete, :desc, :time, :name, :user_id])
    |> validate_required([:complete, :desc, :name])
  end
end

lib/tasktracker/tasks.ex
defmodule Tasktracker.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias Tasktracker.Repo

  alias Tasktracker.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id), do: Repo.get!(Task, id)

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    IO.inspect attrs
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end

  def list_tasks(user_id) do
    query = from t in Task,
      where: t.user_id == ^user_id,
      select: t
    Repo.all(query)
  end
end

lib/tasktracker/tasks/task.ex
defmodule Tasktracker.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tasks" do
    field :complete, :boolean, default: false
    field :desc, :string
    field :time, :integer
    field :title, :string
    belongs_to :user, Tasktracker.Users.User
    has_many :timeblock, Tasktracker.TimeBlocks.TimeBlock, foreign_key: :task_id

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    attrs = if attrs != nil && Map.has_key?(attrs, "name") &&
               Tasktracker.Users.get_user_by_name(attrs["name"]) do
      user = Tasktracker.Users.get_user_by_name(attrs["name"])
      Map.put(attrs, "user_id", user.id)
      |> Map.delete("name")
    else
      attrs
    end

    cast(task, attrs, [:title, :desc, :time, :complete, :user_id])
    |> validate_required([:title, :desc, :complete])
  end
end

lib/spatracker_web/controllers/task_controller.ex
defmodule SpatrackerWeb.TaskController do
  use SpatrackerWeb, :controller

  alias Spatracker.Tasks
  alias Spatracker.Tasks.Task

  action_fallback SpatrackerWeb.FallbackController

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    IO.inspect tasks
    render(conn, "index.json", tasks: tasks)
  end

  def create(conn, %{"task" => task_params}) do
    with {:ok, %Task{} = task} <- Tasks.create_task(task_params) do
      conn
      |> put_status(:created)
      |> put_resp_header("location", Routes.task_path(conn, :show, task))
      |> render("show.json", task: task)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    render(conn, "show.json", task: task)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)

    with {:ok, %Task{} = task} <- Tasks.update_task(task, task_params) do
      render(conn, "show.json", task: task)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)

    with {:ok, %Task{}} <- Tasks.delete_task(task) do
      send_resp(conn, :no_content, "")
    end
  end
end

lib/spatracker_web/views/task_view.ex
defmodule SpatrackerWeb.TaskView do
  use SpatrackerWeb, :view
  alias SpatrackerWeb.TaskView
  alias Spatracker.Repo

  def copyTaskWithoutUserSchema(task) do
    task = Repo.preload(task, :user)
    if task.user do
      Map.put(task, :user, task.user.name)
    else
      task
    end
  end

  def render("index.json", %{tasks: tasks}) do
    #tasks = Enum.map(tasks, &copyTaskWithoutUserSchema/1)
    %{data: render_many(tasks, TaskView, "task.json")}
  end

  def render("show.json", %{task: task}) do
    #task = copyTaskWithoutUserSchema(task)
    %{data: render_one(task, TaskView, "task.json")}
  end

  def render("task.json", %{task: task}) do
    task = copyTaskWithoutUserSchema(task)
    %{id: task.id,
      complete: task.complete,
      name: task.name,
      user: task.user,
      desc: task.desc,
      time: task.time}
  end
end

lib/tasktracker_web/controllers/task_controller.ex
defmodule TasktrackerWeb.TaskController do
  use TasktrackerWeb, :controller

  alias Tasktracker.Tasks
  alias Tasktracker.Tasks.Task
  alias Tasktracker.Repo

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    |> Repo.preload(:timeblock)
    |> Repo.preload(:user)
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Tasks.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"task" => task_params}) do
    case Tasks.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    |> Repo.preload(:timeblock)
    |> Repo.preload(:user)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    changeset = Tasks.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)

    IO.inspect task_params
    case Tasks.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    {:ok, _task} = Tasks.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end
end

lib/tasktracker_web/views/task_view.ex
defmodule TasktrackerWeb.TaskView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/task/edit.html.eex
<h1>Task <small class="text-muted"><%= @task.title %></small></h1>
<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

lib/tasktracker_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title %>
    <%= text_input f, :title, class: "form-control", required: "true" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :desc %>
    <%= text_input f, :desc, class: "form-control", required: "true" %>
    <%= error_tag f, :desc %>
  </div>

  <div class="form-group">
    <%= label f, :complete %>
    <%= checkbox f, :complete %>
    <%= error_tag f, :complete %>
  </div>

  <%= if @current_user do %>
    <div class="form-group">
      <%= label f, :assignee %>
      <%= select f, :name, [""] ++ Enum.map(@current_user.underling, fn u -> u.name end) %>
    </div>
  <% end %>


  <div>
    <%= submit "Save", class: "btn btn-primary" %>
    <%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-dark" %>
  </div>
<% end %>

lib/tasktracker_web/templates/task/index.html.eex
<h1>All <small class="text-muted">Tasks</small></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Status</th>
      <th>Assignee</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.desc %></td>
      <td><%= if task.title == true do %> Complete
          <% else %> Incomplete <% end %></td>
      <td><%= if task.user, do: task.user.name%></td>
      <td>
        <%= link "Show", to: Routes.task_path(@conn, :show, task),
            class: "btn btn-secondary" %>
        <%= link "Edit", to: Routes.task_path(@conn, :edit, task),
            class: "btn btn-info" %>
        <%= link "Delete", to: Routes.task_path(@conn, :delete, task),
            method: :delete, data: [confirm: "Are you sure?"],
            class: "btn btn-danger" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span>
  <%= link "New Task", to: Routes.task_path(@conn, :new), class: "btn btn-primary" %>
</span>

lib/tasktracker_web/templates/task/new.html.eex
<h1>New Task</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

lib/tasktracker_web/templates/task/show.html.eex
<h1>Task <small class="text-muted"><%= @task.title %></small></h1>

<ul class="list-group">
  <li class="list-group-item">
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li class="list-group-item">
    <strong>Desc:</strong>
    <%= @task.desc %>
  </li>

  <li class="list-group-item">
    <strong>Status:</strong>
    <%= if @task.complete do %>
      Complete
    <% else %>
      Incomplete
    <% end %>
  </li>

  <li class="list-group-item">
    <strong>Assignee:</strong>
    <%= if @task.user, do: @task.user.name %>
  </li>

  <script>
    window.timeblock_path = "<%= Routes.time_block_path(@conn, :create) %>";
  </script>

  <li class="list-group-item">
    <strong>Time Blocks:</strong><p>Displayed in Posix Time</p>
    <ul>
      <li>
        <button id = "start-button" class="btn btn-success" data-task-id="<%=@task.id %>">Start</button>
        <button id = "end-button" class="btn btn-danger" data-task-id="<%=@task.id %>">Stop</button>
      </li>
      <%= for t <- @task.timeblock do %>
        <li>
          <div>
            <input type="number" id="start<%= t.id %>" value="<%= t.start %>"></input> to
            <input type="number" id="end<%= t.id %>" value="<%= t.end %>"></input>
            <button data-path="<%= Routes.time_block_path(@conn, :update, t.id) %>"
             class="btn btn-info edit-timeblock" data-tb-id="<%= t.id %>">edit</button>
          </div>
        </li>
      <% end %>
    </ul>
  </li>

</ul>

<span><%= link "Edit", to: Routes.task_path(@conn, :edit, @task), class: "btn btn-info" %></span>
<span><%= link "Back", to: Routes.task_path(@conn, :index), class: "btn btn-dark" %></span>