lib/spatracker_web/router.ex
defmodule SpatrackerWeb.Router do
  use SpatrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", SpatrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", SpatrackerWeb do
  #   pipe_through :api
  # end

  scope "/api/v1", SpatrackerWeb do
    pipe_through :api

    resources "/users", UserController, except: [:new, :edit]
    resources "/tasks", TaskController, except: [:new, :edit]
    post "/auth", AuthController, :authenticate
  end
end

lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TasktrackerWeb.Plugs.FetchSession
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :ajax do
    plug :accepts, [":json"]
    plug :fetch_session
    plug :fetch_flash
    plug TasktrackerWeb.Plugs.FetchSession #FIXME "FetchUser"
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/tasks", TaskController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TasktrackerWeb do
    pipe_through :ajax
    resources "/timeblocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/spatracker_web/views/layout_view.ex
defmodule SpatrackerWeb.LayoutView do
  use SpatrackerWeb, :view
end

lib/tasktracker_web/views/layout_view.ex
defmodule TasktrackerWeb.LayoutView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TaskTracker · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="navbar-brand mr-auto">
          <%= link "Task Tracker", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
        </div>
        <div>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link "Tasks", to: Routes.task_path(@conn, :index), class: "nav-link" %>
            </li>
            <li class"nav-item">
              <%= link "Users", to: Routes.user_path(@conn, :index), class: "nav-link" %>
            </li>
            <li>
            <%= if @current_user do %>
              <div class="dropdown navbar-nav">
                <button class="btn btn-secondary dropdown-toggle" type="button" 
                        id="dropdownMenuButton" data-toggle="dropdown" 
                        aria-haspopup="true" aria-expanded="false">
                        <%= @current_user.name %>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <%= link("Profile", to: Routes.user_path(@conn, :show, @current_user),
                    class: "dropdown-item") %>
                  <%= link("Logout", to: Routes.session_path(@conn, :delete),
                    method: :delete, class: "dropdown-item") %>
                </div>
              </div>
            <% end %>
            </li>
          </ul>
        </div>
      </nav>

      <div class="row">
        <div class="col-12">
          <%= if get_flash(@conn, :info) do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error) do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-8">
          <%= render @view_module, @view_template, assigns %>
        </div>

        <div class="col-4">
          <%= if @current_user do %>
            <p class="my-3">
            <table class="table table-bordered">
              <thead>Current Tasks</thead>
              <tr>
                <th>Title</th>
                <th>Status</th>
                <th>View</th>
                <th>Delete</th>
              </tr>
              <%= for task <- @current_tasks do %>
                <tr>
                  <td><%= task.title %></td>
                  <td><%= if task.complete do %>
                        Complete
                      <% else %>
                        Incomplete
                      <% end %>
                  </td>
                  <td><%= link "Show", to: Routes.task_path(@conn, :show, task),
                    class: "btn btn-link" %></td>
                  <td><%= link "Delete", to: Routes.task_path(@conn, :delete, task),
                    method: :delete, data: [confirm: "Are you sure?"],
                    class: "btn btn-link" %></td>
                </tr>
              <% end %>
            </table>
          <% else %>
            <%= form_for @conn, Routes.session_path(@conn, :create),
              [class: "form-inline"], fn f -> %>
              <%= text_input f, :name, class: "form-control" %>
                <%= submit "Login", class: "btn btn-secondary" %>
           <% end %>
         <% end %>
       </div>
     </div>
</div>

    <script type="text/javascript" src="<%= Routes.static_url(@conn, "/js/app.js") %>"></script>
  </body>
</html>